# Configuracion para que no se registre en el micriservicio de eureka ya que no es necesario
eureka:
  client:
    register-with-eureka: false


server:
  port: 8080

spring:
  application:
    name: afhb-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**
