server:
  port: 8761

spring:
  application:
    name: afhb-eureka

# Configuracion del servidor eureka para que los microservicios se puedan inscribir en el
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/